name: Greeting Worklow

on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Nice Job!"
      - name: Print Goodbye
        run: echo "Done, Bye!"