name: Greeting Worklow

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Nice Job!"
      - name: Print Goodbye
        run: echo "Done, Bye!"