name: Push Test

on: push

jobs:
  push_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install Dependencies
        run: uv sync
      - name: Run Scripts
        run: uv run main.py