name: Push Test

on: push

jobs:
  push_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Run Code
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
      - run: python main.py